[package]
name = "deptr"
version = "0.3.2"
edition = "2021"
description = "A dependency tracker to identify unused dependencies in projects"
authors = ["Sam Atkins"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
rustpython-parser = "0.3.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
toml = "0.8.10"

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.1.0"
