[package]
name = "deptr"
version = "0.3.1"
edition = "2021"
description = "A dependency tracker to identify unused dependencies in projects"
authors = ["Sam Atkins"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
rustpython-parser = "0.3.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.109"
toml = "0.8.8"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.1.0"
